services:
  # Based on https://gal.hagever.com/posts/running-vercel-postgres-locally and
  # https://github.com/neondatabase/wsproxy
  db:
    image: "postgres:17.0-alpine"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: ryoko
    ports:
      - "5432:5432"
    # Configure container to support SSL/TLS, so that the application doesn't need a special, insecure mode for local development.
    # Inspired by https://github.com/docker-library/postgres/issues/989
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./scripts/server.crt:/var/lib/postgresql/server.crt
      - ./scripts/server.key:/var/lib/postgresql/server.key
