compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
main = "src/main.ts"
name = "ryoko"

# [vars]
# EXAMPLE = "example"

# [ai]
# binding = "AI"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [observability]
# enabled = true
# head_sampling_rate = 1

# [[hyperdrive]]
# binding = "HYPERDRIVE"
# id = "<ID OF THE CREATED HYPERDRIVE CONFIGURATION>"
